main/default/objects/Nace_sectors__c/Nace_sectors__c.object-meta.xml
<CustomObject>
    <label>NACE Activity</label>
    <nameField>
        <label>NACE Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NACE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Nace_sectors__c/fields/Parent_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Code</label>
    <referenceTo>Nace_sectors__c</referenceTo>
    <relationshipName>NACE_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Nace_sectors__c/fields/RootLocationId__c.field-meta.xml
<CustomField>
    <fullName>RootLocationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RootLocationId</label>
    <referenceTo>Nace_sectors__c</referenceTo>
    <relationshipName>NACE_Sectors1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/LocationTreeControllerTest.cls
@isTest(SeeAllData=true)
public with sharing class LocationTreeControllerTest {
    
    @isTest(SeeAllData=true)
    public static void doTest() {
        List<Nace_sectors__c> naceRootID = new List<Nace_sectors__c>([SELECT Id FROM Nace_sectors__c WHERE External_Id__c = 'extID-999999']);
        //System.debug(naceRootID);
        ID nrId = naceRootID[0].Id;
        //Id naceRootID = [SELECT Id FROM Nace_sectors__c WHERE External_Id__c = 'extID-999999' LIMIT 1].Id;
        //System.debug('CG:: ID is ' + naceRootID.to15());
        
        Schema.Nace_sectors__c loc = new Schema.Nace_sectors__c(
            Name='Test NACE',
            RootLocationId__c = naceRootID[0].Id,
            Parent_Code__c = naceRootID[0].Id
            );
        insert loc;
        LocationTreeController.getHierarchy(loc.id);
    }
    
}